### ISSUE TITLE
Not connected to Ledger Nano X

### ISSUE THREAD

**Issue by ElvisPresly** [Bertrand256/dash-masternode-tool#45] opened 2022-04-29 08:40 UTC
I installed the latest ledger dash app. And DMT stopped connecting
<img width="1024" alt="Снимок экрана 2022-04-29 в 11 40 25" src="https://user-images.githubusercontent.com/18265958/165911879-9cee9c87-2065-4664-ad31-aaa2f9351554.png">

**Comment by Bertrand256** [comment] 2022-04-29 10:05
For now I can only confirm that the problem actually exists, but at the moment I don't know if it's caused by the new version of Dash.app or by the Ledger Python client library that DMT uses.

**Comment by Bertrand256** [comment] 2022-04-29 10:55
> DMT was the only one app that allowed you to spend rewards from Ledger

I'll try to resolve it but I can't promise when - workarounds to the changes that Ledger sometimes made often required a lot of work (time).

**Comment by Bertrand256** [comment] 2022-05-01 18:30
The problem is resolved in DMT v0.9.31. Please check if it works for you.

**Comment by ElvisPresly** [comment] 2022-05-02 05:58
> The problem is resolved in DMT v0.9.31. Please check if it works for you.

its worked
Thank you

**Closed** 2022-05-02 06:01 UTC
