### ISSUE TITLE
can't send funds

### ISSUE THREAD

**Issue by TanteStefana** [Bertrand256/dash-masternode-tool#46] opened 2022-08-31 08:34 UTC
last step, "Send Transaction" gives error as follows:

An error occurred while sending transation: -8: Second argument must be numeric (maxfeerate) and no longer supports a boolean. To allow a transaction with high fees, set maxfeerate to 0.

xk nft notes that there were some RPC changes in v18, could that be the cause?

**Comment by Bertrand256** [comment] 2022-08-31 08:36
I'll check that out. Thanks for reporting.

**Comment by TanteStefana** [comment] 2022-08-31 08:41
Same issue is being reported on Telegram buy another person, fyi (I'm hoping it's not my trezor, LOL)

**Comment by Bertrand256** [comment] 2022-08-31 08:48
Theoretically, it could be Trezor or its libraries not being adapted to the latest changes, but it should also be possible to prepare a workaround, as has been done in the past.

**Comment by babygiraffe05** [comment] 2022-09-01 00:42
I can confirm this behavior as well using a KeepKey. I am getting an identical error code regardless of whether I am directly connected to my own local node or connected through alice.dash-masternode-tool.org or suzy.dash-masternode-tool.org. It gives the same error for all three connection types.

**Comment by TanteStefana** [comment] 2022-09-01 03:44
Glad to see you around Ryan :D

**Comment by babygiraffe05** [comment] 2022-09-01 22:02
Good to "see" you too.

Given this has occurred with BOTH KeepKey and Trezor, I think we can pretty reliably rule out the possibility of the hardware wallets themselves being the problem. DMT hasn't had an updated version in a while, so it was stable. My hypothesis is that this might have been due to a change introduced in Core v18, especially if alice and suzy are both upgraded to v18.

**Comment by Bertrand256** [comment] 2022-09-02 07:26
I have found a solution. The reason is the slightly changed API in v18. Today I should be able to publish fixed version.

**Comment by Bertrand256** [comment] 2022-09-02 17:47
@TanteStefana @babygiraffe05 

Fixed in v0.9.32 (https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.32)

**Comment by TanteStefana** [comment] 2022-09-02 23:01
Awesome, thank you so much!!!

**Comment by babygiraffe05** [comment] 2022-09-03 16:21
Thank you! Great work, and fast too.

**Comment by Bertrand256** [comment] 2022-09-03 20:48
I'm closing the issue. Feel free to reopen it if you find any problems with the fix.

**Closed by Bertrand256** 2022-09-03 20:48 UTC
